# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CloudWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Cloud(object):
    def setupUi(self, Cloud):
        Cloud.setObjectName("Cloud")
        Cloud.resize(612, 644)
        self.pushButton = QtWidgets.QPushButton(Cloud)
        self.pushButton.setGeometry(QtCore.QRect(74, 180, 81, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Cloud)
        self.pushButton_2.setGeometry(QtCore.QRect(64, 240, 91, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Cloud)
        self.pushButton_3.setGeometry(QtCore.QRect(80, 300, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Cloud)
        self.pushButton_4.setGeometry(QtCore.QRect(80, 360, 75, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label = QtWidgets.QLabel(Cloud)
        self.label.setGeometry(QtCore.QRect(230, 180, 54, 12))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Cloud)
        self.label_2.setGeometry(QtCore.QRect(240, 240, 54, 12))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Cloud)
        self.label_3.setGeometry(QtCore.QRect(240, 310, 54, 12))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Cloud)
        self.label_4.setGeometry(QtCore.QRect(240, 370, 54, 12))
        self.label_4.setObjectName("label_4")
        self.pushButton_5 = QtWidgets.QPushButton(Cloud)
        self.pushButton_5.setGeometry(QtCore.QRect(170, 460, 75, 23))
        self.pushButton_5.setObjectName("pushButton_5")

        self.retranslateUi(Cloud)
        QtCore.QMetaObject.connectSlotsByName(Cloud)

    def retranslateUi(self, Cloud):
        _translate = QtCore.QCoreApplication.translate
        Cloud.setWindowTitle(_translate("Cloud", "Form"))
        self.pushButton.setText(_translate("Cloud", "打开参数文件"))
        self.pushButton_2.setText(_translate("Cloud", "打开时序影像"))
        self.pushButton_3.setText(_translate("Cloud", "打开掩膜"))
        self.pushButton_4.setText(_translate("Cloud", "保存路径"))
        self.label.setText(_translate("Cloud", "TextLabel"))
        self.label_2.setText(_translate("Cloud", "TextLabel"))
        self.label_3.setText(_translate("Cloud", "TextLabel"))
        self.label_4.setText(_translate("Cloud", "TextLabel"))
        self.pushButton_5.setText(_translate("Cloud", "执行"))
