# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fusionWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Fusion(object):
    def setupUi(self, Fusion):
        Fusion.setObjectName("Fusion")
        Fusion.resize(655, 498)
        self.label = QtWidgets.QLabel(Fusion)
        self.label.setGeometry(QtCore.QRect(50, 90, 171, 18))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Fusion)
        self.label_2.setGeometry(QtCore.QRect(50, 150, 161, 18))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Fusion)
        self.label_3.setGeometry(QtCore.QRect(50, 260, 161, 18))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Fusion)
        self.label_4.setGeometry(QtCore.QRect(50, 310, 151, 18))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Fusion)
        self.label_5.setGeometry(QtCore.QRect(50, 210, 161, 18))
        self.label_5.setObjectName("label_5")
        self.comboBox = QtWidgets.QComboBox(Fusion)
        self.comboBox.setGeometry(QtCore.QRect(260, 90, 90, 24))
        self.comboBox.setObjectName("comboBox")
        self.comboBox_2 = QtWidgets.QComboBox(Fusion)
        self.comboBox_2.setGeometry(QtCore.QRect(280, 160, 90, 24))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_3 = QtWidgets.QComboBox(Fusion)
        self.comboBox_3.setGeometry(QtCore.QRect(280, 210, 90, 24))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_4 = QtWidgets.QComboBox(Fusion)
        self.comboBox_4.setGeometry(QtCore.QRect(280, 250, 90, 24))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_5 = QtWidgets.QComboBox(Fusion)
        self.comboBox_5.setGeometry(QtCore.QRect(280, 300, 90, 24))
        self.comboBox_5.setObjectName("comboBox_5")
        self.pushButton = QtWidgets.QPushButton(Fusion)
        self.pushButton.setGeometry(QtCore.QRect(50, 370, 81, 41))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Fusion)
        QtCore.QMetaObject.connectSlotsByName(Fusion)

    def retranslateUi(self, Fusion):
        _translate = QtCore.QCoreApplication.translate
        Fusion.setWindowTitle(_translate("Fusion", "Fusion"))
        self.label.setText(_translate("Fusion", "基时相高分辨率影像"))
        self.label_2.setText(_translate("Fusion", "基时相低分辨率影像"))
        self.label_3.setText(_translate("Fusion", "分割影像"))
        self.label_4.setText(_translate("Fusion", "输出路径"))
        self.label_5.setText(_translate("Fusion", "预测时相低分辨率影像"))
        self.pushButton.setText(_translate("Fusion", "PushButton"))
